apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  namespace: enterprise-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: enterprise-employee:dev
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8070
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://ep-old-bread-a4lduu7m-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require"
          - name: SPRING_DATASOURCE_USERNAME
            value: "neondb_owner"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "npg_cx0ZlPBeyT6R"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8070
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8070
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  namespace: enterprise-dev
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 31083
  type: NodePort


